### ISSUE TITLE
Status Bar Delete

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#112]
very dated design tbh, but there's functionality so we need a discussion:

- add playlist: duplicates a context menu
- shuffle: it's set and forget move it to prefs window, indicate by changing next track button to shuffle icon
- repeat: it's set and forget, move it to prefs window
- database info: unnecessary
- infopanel toggle: it's getting cut I don't need to toggle it
- eq: make it a dialog and access it from the gear menu

**Comment by danrabbit** [comment]
Closing this as an invalid group issue report. Please open individual issues for each change and use Projects to manage groups of related issues
