### ISSUE TITLE
Move repeat chooser to header bar

### ISSUE THREAD

**Issue by Bat41** [elementary/music#117]

**Comment by danrabbit** [comment]
I'm -1 on this. I don't think it's good to hide away more things in the preferences dialog

**Comment by Bat41** [comment]
Maybe we could move it next to the seekbar then?

**Comment by danrabbit** [comment]
Yeah there is an old mockup with the shuffle and repeat buttons stacked vertically next to the seekbar. Seems like an okay choice:

![music](https://user-images.githubusercontent.com/7277719/33518846-e1f537b2-d750-11e7-8541-45eb453070e7.png)

**Comment by artemanufrij** [comment]
wow that looks nice! @danrabbit it's ok for you if I also move "repeat" and "shuffle" buttons into headerbar in my music player?

**Comment by danrabbit** [comment]
It’s not patented, you can do what you like :p

**Comment by Nine-H** [comment]
I'm OK with this design, but I want mode setting in preferences, because no
apps have had context menus on buttons since luna, and I don't think most
people know we have shuffle and repeat modes.

**Comment by Nine-H** [comment]
lol can't add attachments to email comments wtf

![playback prefs](https://user-images.githubusercontent.com/20123543/33524387-92738196-d870-11e7-9cc0-57e947ef2355.png)

**Comment by cassidyjames** [comment]
Other services seem to use a three-state repeat and a two-state shuffle: repeat none/all/song, and shuffle off/on. I would be fine with simplifying to that; I actually never knew there was a hidden context menu with more options.

**Comment by Bat41** [comment]
I think I'll update #88 to use a three state button for the repeat mode, and a drop the context menu on both of the buttons.
