### ISSUE TITLE
Unify source under one src/ tree

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#138]
the core/app design is entirely for the plugin system, we're cutting plugins, we can pull everything back together into one app.

**Comment by Bat41** [comment]
According to @tintou, dropping the plugin system is a bad idea. Having plugins make the app easier to maintain (it forces you to separate things) and allow us to integrate with as many services/devices/whatever as we want, while allowing you to use only the ones you really need.

**Comment by Nine-H** [comment]
it introduced alot of abstraction and is the primary reason why I'm chasing my tail through multiple classes to try to find anything.

**Comment by danrabbit** [comment]
Closing this since the plugin system is still necessary and desired for things like streaming services
