### ISSUE TITLE
Suggestion: Integration with online services

### ISSUE THREAD

**Issue by geovannikun** [elementary/music#159]
I saw somewhere a doubt about the future of music app, because people are focusing in online services and are not using local players anymore.

Can be that integration with [mopidy](https://www.mopidy.com/) could solve that problem.

**Comment by cassidyjames** [comment]
I'd prefer closing this in favor of more specific, per-service issues. I've opened Spotify as #167 since I know they have some sort of API.

**Comment by Bat41** [comment]
Closing in favor of more specific issues.
