### ISSUE TITLE
Play songs from Spotify

### ISSUE THREAD

**Issue by cassidyjames** [elementary/music#167]
We've been talking in Slack about seeing if we can use the Spotify API for Music, but I noticed there was no record of that here. :stuck_out_tongue:

**Comment by cassidyjames** [comment]
From my previous research into Spotify, I recall that it required a premium account. We'd have to add authentication and then decide how it should show up alongside local music.

**Comment by Bat41** [comment]
According to [their docs](https://developer.spotify.com/web-api/tutorial/), we don't need a premium account to use the API, a normal one is fine.

**Comment by Bat41** [comment]
And to integrate songs from Spotify or other streaming services in the library, I think we can display their logo in a corner of the album art, or with an icon in the list view. We should also have a "Spotify" button/tab (I don't know what's the correct name for that) in the sidebar, in the "Library" section, to browse songs or playlists that have not been added to your local library yet.

**Comment by cassidyjames** [comment]
@Bat41 that's just their Web API docs which doesn't include streaming capabilities.

According to [their docs](https://developer.spotify.com/technologies/libspotify/), they have "upcoming embedded libraries for Windows, Mac OS X and Linux" but they're not out yet. This is effectively blocked unless or until those APIs are out for Linux.

**Comment by geovannikun** [comment]
![elementaryspotify](https://user-images.githubusercontent.com/4943174/33583617-677bfcd4-d942-11e7-8b29-64321834d10f.png)
This is my contribution about how could be the integration with spotify.

About account, the best way could be connecting using the 'Online Accounts' from settings.

**Comment by ramirocantu** [comment]
I feel like it would be a better idea for local and online media to be displayed together with a switch to display only local media. That way people are not having their music collection split into different tabs

**Comment by biswaz** [comment]
@cassidyjames Is slack channel private or is there a public one?

**Comment by cassidyjames** [comment]
@biswaz I was probably talking about the private Slack (basically the elementary corporate office), but there's also the Community Slack at https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc

**Comment by SixFingeredAmish** [comment]
@BaptisteGelez for 3rd party apps, you'd need Spotify Premium I believe.

**Comment by aadilayub** [comment]
I saw that Clementine player has a plugin for Spotify playback. I wonder how they accomplished it, and whether it requires a premium account. http://spotify.clementine-player.org/

**Comment by biswaz** [comment]
Ive seeb players usually getting the user's song list from Spotify and
playing the songs from YouTube.

Regards,
Biswas

**Comment by BaptisteGelez** [comment]
It looks like Clementine uses the deprecated `libspotify`… https://spotify.clementine-player.org/README

**Comment by cassidyjames** [comment]
@biswaz that's just introducing yet another API and/or reverse-engineered solution, as I'm fairly certain stripping audio from YouTube and not displaying the ads is strictly against their terms of service.

**Comment by SixFingeredAmish** [comment]
It's also inelegant

**Comment by biswaz** [comment]
Yes, it is against their policies. We can only show the video. I also agree
that it is not an elegant solution.

**Comment by aadilayub** [comment]
> It looks like Clementine uses the deprecated `libspotify`… https://spotify.clementine-player.org/README

@BaptisteGelez  Is it possible to use the same in Music? Or does `libspotify` no longer work?

**Comment by SixFingeredAmish** [comment]
The reality is the vast majority of users will download the Spotify app and be perfectly happy listening to Spotify from there, where the experience will be identical to their phones.

**Comment by eljefuri** [comment]
_[Commenting because there is a discussion [elsewhere](#447) about Music being dropped in the next version of Elementary.]_

Although Spotify is popular, it is far from ubiquitous. It is not available in every country around the world, and for that matter neither is persistent high-speed Internet access: Given those data points and what we know of Spotify's user numbers, it's entirely probable that there are millions more people playing digital audio files than actively using Spotify on a daily basis. To add one more point, I will continue using digital files that I actually own, and will probably never subscribe to a streaming service.

I would ask that you consider whether the fate of your Music application -- whether it lives or dies -- should really be determined by the momentary popularity of a proprietary, completely centralized, and clearly monopolistically-intentioned platform. It doesn't really fit with what I understand of Elementary's intentions. As an alternative to dropping Music altogether due to assumptions about a "vast majority", please consider asking Artem Anufrij to allow his very stable Melody application to be the default music application in Elementary. It's quite good!

**Comment by aadilayub** [comment]
I wouldn't paint so dire a picture about the future of Music. However, I would like to add that there are many countries where Spotify, Apple Music, Google Play Music, are not available. In these countries, a lot of people still maintain local music libraries on their computers.

**Comment by alexandremagro** [comment]
@cassidyjames is this still "technically infeasible"? I fell into this discussion after trying to understand why Elementary's Music does not have this functionality, and there are (non-curated apps) players in the store that do this integration.

**Comment by quassy** [comment]
Would Apple Music be a viable alternative? There seem to be some third-party music players out there already like https://github.com/falcon78/Vusic, maybe Apple is more developer-friendly?

**Comment by guillermoap** [comment]
Is this still an active discussion? The spotify client gets worse everyday.

**Comment by tintou** [comment]
There is no possible way that this issue can be solved as Spotify is a closed platform which doesn't provide a usable SDK.

**Comment by Suzie97** [comment]
https://github.com/xou816/spot, just wanted to share this new native GNOME Spotify client. Its in development.
