### ISSUE TITLE
No album art is shown

### ISSUE THREAD

**Issue by o-alquimista** [elementary/music#179]
For each music folder, I place a cover.jpg or folder.jpg image inside. The audio files are tagged appropriately, and the album arts are shown in other music players. Noise won't show any of them.

![captura de tela de 2017-12-04 23-31-38](https://user-images.githubusercontent.com/25424263/33585436-6b7930dc-d94b-11e7-92e4-24715e695fe2.png)
![captura de tela de 2017-12-04 23-32-25](https://user-images.githubusercontent.com/25424263/33585438-6bd91fa6-d94b-11e7-9710-fa5c0c94bff4.png)

Workarounds tried:
- deleted music database at ~/.local/share/noise/

**Comment by Nine-H** [comment]
you can add album art manually by right clicking the blank art on the album popup.

**Comment by Bat41** [comment]
It will be fixed by #89
