### ISSUE TITLE
Selecting shuffle chooser resets view to list view [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#186]
Every time you change shuffle mode you get kicked to list view and the view chooser becomes insensitive

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/52352815-selecting-shuffle-chooser-resets-view-to-list-view)

**Comment by Bat41** [comment]
I can reproduce, but only if music is playing.

**Comment by Nine-H** [comment]
This seems related to search and the modebutton being set insensitive. There's also some weird shit going on in `src/Widgets/ViewSelector.vala`

**Comment by danrabbit** [comment]
It seems like this can be reproduced by changing the queue in any way
