### ISSUE TITLE
X11 media keys being hijacked

### ISSUE THREAD

**Issue by aknobloch** [elementary/music#227]
Trying to grab media keys in particular using X11 end up being hijacked sporadically by something. The expected behavior is that elementaryOS would honor grab keys and trying to do a passive grab later would return BadAccess errors when another program tries to passively grab a key. However, X11 will report the keys as being successfully grabbed, and they will work for a while, until they are seemingly randomly hijacked back. After keys are hijacked, another grab needs to be issued, or else it is redirected and a pop up in the top right occurs. Not sure if this pop up is a specific preloaded media application, or a function of the OS itself. A quick way to replicate this is to grab the keys like normal, and then toggle num-lock. That seems to trigger the hijack event.

A very simple example below:
This can be compiled using `g++ filename.cpp $(pkg-config --cflags --libs x11) -o xgrabkey`

```c++
#include <iostream>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
using namespace std;

int main()
{

    Display* dpy = XOpenDisplay(0);
    Window root = DefaultRootWindow(dpy);
    unsigned int modifiers = AnyModifier;
    Bool owner_events = False;
    int pointer_mode = GrabModeAsync;
    int keyboard_mode = GrabModeAsync;

    XEvent event;
    
    int media_previous = 173;
    XGrabKey(dpy, media_previous, modifiers, root, owner_events, pointer_mode, keyboard_mode);

    while(true)
    {
        XNextEvent(dpy, &event);

        switch(event.type)
        {
            case KeyPress:

            cout << "Key pressed." << endl;
        }
    }

    XCloseDisplay(dpy);
    return 0;
}
```

Another odd thing I noticed is that when going into the settings > keyboard > media, it lists all shortcuts as disabled. However, when clicking on one to reassign, it pops up "WARNING! Key is already assigned to Disabled." Ignoring this and mapping it to the appropriate key will keep the status as "disabled," but won't interfere with keygrabs anymore. This is obviously very strange behavior. Not sure if this belongs in a different repository, so sorry if there's a better place.

**Comment by danrabbit** [comment]
This is probably better at https://github.com/elementary/gala

Music itself doesn't listen for any media keys, it just uses the MPRIS interface on DBus. Closing as "Out of scope"
