### ISSUE TITLE
use the --nonet argument for appstreamcli

### ISSUE THREAD

**Issue by decathorpe** [elementary/music#268]
It's good to see this project has been ported to meson, but there are some regressions present right now:

- [x] Only an unversioned .so file is installed into LIBDIR anymore, which is bad. The `.so` library should be versioned (it was previously `.so.0.1`) and the unversioned `.so` (and `.so.0`) should only be symlinks to the versioned one. meson should be able to do it like that automatically, too (it's how shared libraries are supposed to work on linux after all, so it shouldn't be too difficult)

- [x] `LIBDIR/music/` is a too generic location for this project's plugins directory. It used to be `LIBDIR/io.elementary.music/`. I guess this is a mistake that was made during the porting.

- [x] The icon is installed into the wrong directory (`/usr/share/icons/hicolor/` instead of `/usr/share/icons/hicolor/scalable/apps/`. This looks like a copy-paste error from CMake.

- [ ] Please use the `--nonet` argument for `appstreamcli` so the tests can be executed offline, too.

**Comment by tintou** [comment]
@decathorpe `--nonet` is far from being available everywhere, so it might not be possible for us to do anything right now

**Comment by decathorpe** [comment]
@tintou Ok, that's a valid point. That is the least important point anyway. It just means that I can't run the upstream test suite during fedora builds.

**Comment by decathorpe** [comment]
This has been resolved in https://github.com/ximion/appstream/commit/c4f71f3650d8cabea0db6b0f8120a7790183f69a - I can set the `AS_VALIDATE_NONET` environment variable to disable tests that require an active internet connection. So, I'm closing this issue :slightly_smiling_face:
