### ISSUE TITLE
Changes to music folder location are not persistent

### ISSUE THREAD

**Issue by lwtw** [elementary/music#295]
When I go to Music's preferences and set the music folder location from - in my case - `~/Music` to `~/Music/Library`, the changes are applied as expected. However, if I close Music and reopen it, it reverts to the previous configuration, which means I can only change the music location temporarily.

I am using Elementary OS 0.4.1 Loki, problems still exists after `sudo apt-get update && sudo apt-get upgrade`.

**Comment by MrVoltz** [comment]
I'm facing the same issue. I've browsed the source code and didn't find anything that could be saving the location persistently. A workaround is to change the library location using dconf-editor.

**Comment by Mohelm97** [comment]
This issue is half solved, You can change the library location, but only using the "Other" option in the list, if you choose anything from the list nothing will happen (Not even loading)
