### ISSUE TITLE
Ability to add other categories under "Library" in left sidebar

### ISSUE THREAD

**Issue by eosuser** [elementary/music#303]
I would like the ability add categories other than "Music" under "Library" in the left sidebar so that each category has its own folder location and shuffle-play is limited to files from the current category.

**Comment by danrabbit** [comment]
This sounds a lot like smart playlists. OP can you maybe clarify how that doesn't solve your issue?

**Comment by eosuser** [comment]
The smart playlist "URI contains" rule solves my issue. I think the idea of having all my audio files, including non-music files, under "Music" threw me off. Thanks.
