### ISSUE TITLE
Don't show Queue menu item while in the queue

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#307]
Makes sense :p

**Comment by danielopitz** [comment]
I'm not so sure here... The usual case would be just to add another entry in the queue for the song. This is how it is handled in virtually every other music player I know which has a playback queue implementation (even dumbed down apps like Apple Music on iOS). 

But current implementation of the queue makes the behaviour buggy: When a song is added multiple times to the playback queue and played, all of the entries are marked as playing and using next / prev does funny stuff.

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.
