### ISSUE TITLE
Google Music Integration

### ISSUE THREAD

**Issue by KeironO** [elementary/music#310]
I was just wondering if there was any chance of Google Music integration through the unofficial ```gmusicapi``` library?

**Comment by BaptisteGelez** [comment]
Integration with streaming services is part of our plans for the future, so why not with Google Music.

**Comment by Suzie97** [comment]
Google Music has been discontinued, and replaced with YouTube Music: https://blog.youtube/news-and-events/youtube-music-will-replace-google-play-music-end-2020/

**Comment by tintou** [comment]
Closing as this issue isn't going to be fixed anytime soon
