### ISSUE TITLE
Music isn't displaying icon in the AppCenter

### ISSUE THREAD

**Issue by btd1337** [elementary/music#334]
version: Juno Beta

![captura de tela de 2018-05-29 01-56-25](https://user-images.githubusercontent.com/11943860/40638825-f3ad4840-62e3-11e8-9bee-96e1d7f46ba6.png)

**Comment by ryonakano** [comment]
I can reproduce this

![screenshot from 2018-05-29 19-28-12](https://user-images.githubusercontent.com/26003928/40653676-d4eedfe8-6376-11e8-9d0c-5cfeee9d07db.png)

**Comment by liamkinne** [comment]
Also having this issue. I'll have a look

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit @cassidyjames The issue is still relevant.Any idea how to solve it?

**Comment by ryonakano** [comment]
@4jNsY6fCVqZv The PR #511 should fix this issue, I've never tested it though.

**Comment by 4jNsY6fCVqZv** [comment]
@ryonakano It would be nice if the PR could fix the issue. Then all we need is a solution for the other apps mentioned.

**Comment by ryonakano** [comment]
Closing since the issue seems to be gone on Hera
