### ISSUE TITLE
can't import music from cd's

### ISSUE THREAD

**Issue by JO0st** [elementary/music#35]
When trying to import music from a cd nothing happens. When music is run from terminal it gives the following output when trying to do so:

    [INFO 11:54:03.760646] CDDA.vala:59: CD ALBUM_NAME: The Late Album
    [INFO 11:54:03.760734] CDDA.vala:60: CD ALBUM_ARTIST: Spencer the Rover
    [INFO 11:54:03.760805] CDDA.vala:61: CD ALBUM_GENRE: (null)
    [FATAL 11:54:03.846160] noise_album_get_cover_icon: assertion 'self != NULL' failed
    [WARNING 11:54:03.863039] SpaceWidget.vala:307: ERROR: SpaceWidget: Couldn't update item [index = 2]. Not enough free space.
    [WARNING 11:54:03.863119] SpaceWidget.vala:307: ERROR: SpaceWidget: Couldn't update item [index = 1]. Not enough free space.
    [INFO 11:54:03.863544] DeviceSummaryWidget.vala:244: refreshing lists
    [INFO 11:54:03.864645] DeviceSummaryWidget.vala:287: setting sensitivity
    [INFO 11:54:03.879904] LibraryWindow.vala:759: new custom device (probably a CD) added with 3441 songs.
    [FATAL 11:54:14.714600] CDRipper.vala:65: Could not create GST Elements for ripping.
    [WARNING 11:54:14.714704] CDRomDevice.vala:259: Could not create CD Ripper

Contrary to what the terminal is saying the cd only contains 9 tracks

**Comment by zigford** [comment]
Same issue here:
`[INFO 18:39:46.385480] CDDA.vala:59: CD ALBUM_NAME: Oh Dear, What Can the matter Be?
[INFO 18:39:46.385507] CDDA.vala:60: CD ALBUM_ARTIST: Jay laga'aia
[INFO 18:39:46.385516] CDDA.vala:61: CD ALBUM_GENRE: (null)
[FATAL 18:39:46.412965] noise_album_get_cover_icon: assertion 'self != NULL' failed
[WARNING 18:39:46.420155] SpaceWidget.vala:307: ERROR: SpaceWidget: Couldn't update item [index = 2]. Not enough free space.
[WARNING 18:39:46.420179] SpaceWidget.vala:307: ERROR: SpaceWidget: Couldn't update item [index = 1]. Not enough free space.
[INFO 18:39:46.420310] DeviceSummaryWidget.vala:244: refreshing lists
[INFO 18:39:46.420635] DeviceSummaryWidget.vala:287: setting sensitivity
[INFO 18:39:46.426293] LibraryWindow.vala:759: new custom device (probably a CD) added with 5046 songs.
[FATAL 18:39:49.992973] CDRipper.vala:65: Could not create GST Elements for ripping.
[WARNING 18:39:49.993004] CDRomDevice.vala:259: Could not create CD Ripper
`
