### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#359]
Our UI has changed, we need to update the screenshot that is referenced by our metadata. I think preferably we should use music that is available in creative commons or other permissive licenses

**Comment by cassidyjames** [comment]
I have a bunch of Humble Bundle soundtracks. They're not strictly permissively licensed (I'll have to check!) but are DRM free at least :man_shrugging:

**Comment by BaptisteGelez** [comment]
I may have some Creative Commons music in my library if needed, too.

**Comment by kgrubb** [comment]
Here's some screenshots with creative commons music:

![Screenshot from 2019-09-13 19 13 50](https://user-images.githubusercontent.com/8471701/64899703-af6bf780-d65a-11e9-858a-d4a190f8e899.png)

![Screenshot from 2019-09-13 19 16 13](https://user-images.githubusercontent.com/8471701/64899763-ffe35500-d65a-11e9-8126-48d3052ca835.png)

![Screenshot from 2019-09-13 19 17 33](https://user-images.githubusercontent.com/8471701/64899804-302af380-d65b-11e9-9a84-41df57479294.png)

**Comment by cassidyjames** [comment]
@kgrubb could you propose a branch that replaces [data/screenshot.png](https://github.com/elementary/music/blob/master/data/screenshot.png) with one of these? You can also add like screenshot-2.png and screenshot-3.png and add them to the XML

https://github.com/elementary/music/blob/6247a60cd28f28531f43b8f4408b31259f0d4ba0/data/io.elementary.music.appdata.xml.in#L149-L153

just make sure the two new ones don't include `type="default"` in the XML.
