### ISSUE TITLE
Make shuffle a boolean setting

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#361]
For some (probably YAGNI) reason it's set up as an enum

**Comment by bjorn** [comment]
I guess it was an enum so later on possibly other modes could be added, like shuffling albums but not shuffling the track list within each album, or the other way around.

Anyway, this was done in #420 but it wasn't merged.

What's the problem with having it as enum? I'd suggest just closing this issue.

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.
