### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/music#37]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.
https://translations.launchpad.net/noise
![captura de tela de 2017-05-27 14-29-03](https://cloud.githubusercontent.com/assets/8754997/26523207/ea360c0a-42e8-11e7-949f-934354db48f6.png)

**Comment by Bat41** [comment]
I think #34 fixed this, right?
