### ISSUE TITLE
Figure out what focus_blacklist is

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#381]
https://github.com/elementary/music/blob/f021f5ccfd500a9b94455b0996c82ba6db4b5551/src/Views/AlbumsView.vala#L74

Anyone know what this is supposed to do?

**Comment by lainsce** [comment]
Looks to be a list of widgets to disable focusing of. After that line, it's adding the statusbar, search entry, a "source list view" and a "view selector". Afterwards, it adds an eventbox to those widgets instead. :thinking:

**Comment by BaptisteGelez** [comment]
@lainsce where does it add an EventBox?

According to Valadoc, it allows the listed widgets to be clicked, but that makes no sense…

**Comment by lainsce** [comment]
In this code, it's adding an eventmask where clicks are allowed:
```
foreach (var w in focus_blacklist) {
            w.add_events (Gdk.EventMask.BUTTON_PRESS_MASK);
}
```

**Comment by danrabbit** [comment]
@BaptisteGelez Yeah that's exactly what it looks like to me too.

I don't think this code makes sense. All of these widgets already send button press events and there's nothing in here that's listening for raw button events

**Comment by BaptisteGelez** [comment]
OK, I found. When it was introduced, it was actually usefull, as it was closing the popup when these widgets got focus: https://github.com/elementary/music/commit/fbf9562927a92199262291abc3d5466210fa26f1#diff-33ed3678ba421f3783b3895e750b5270R157

But for some reason, this part of the code have been removed at some point. I guess you can safely delete it (or re-introduce the feature if you want).
