### ISSUE TITLE
Add command to pause and play music

### ISSUE THREAD

**Issue by frankliu197** [elementary/music#389]
It would be great to add a terminal command to pause/play the music (or even better add the next and previous button as well). This way we could make a keyboard shortcut for all these tasks.

Thanks,
Frank

**Comment by danrabbit** [comment]
You can configure media shortcuts in System Settings → Keyboard → Media :)

![screenshot from 2018-07-03 18 00 20 2x](https://user-images.githubusercontent.com/7277719/42251245-f91e19c6-7eea-11e8-8efb-10fd81a8328b.png)

**Comment by frankliu197** [comment]
Thanks for replying.
I don't know what happened. I actually saw that before posting this because all the keyboard shortcuts play to next track didn't work, but now it works again. Thank you very much.
