### ISSUE TITLE
[i18n]Untranslated components shown in Music

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/music#394]
Untranslated componets shown in Music.
Title, Length, Artist, Album, Genre

**Comment by Nine-H** [comment]
can you provide more details?

- where these untranslated strings appear
- what language you're testing
- what the translation would be in that language

**Comment by ryonakano** [comment]
@bagjunggyu I'm sorry, you've already posted this screenshot on Slack

**Comment by bagjunggyu** [comment]
Yes, those titles of subjects which should be shown as Korean and Japanese as well.
Now I guess that it is missed from the pot, since I searched it at weblate(https://l10n.elementary.io/projects/music/music/ko/) but there is no components above (Title, Length, Artist, Album, Genre)

**Comment by danrabbit** [comment]
Should be fixed by 1eaac21881058074280ead3ab794dd27dda422ec
