### ISSUE TITLE
Can't sort songs in list & column view

### ISSUE THREAD

**Issue by ryonakano** [elementary/music#396]
![peek 2018-07-21 09-48](https://user-images.githubusercontent.com/26003928/43030467-4ff4f61e-8ccb-11e8-8d73-5abc1a3c067c.gif)

Clicking column headers (e.g. Title, Artist, etc.) in list view and column view do nothing. Nothing can be sorted.

With Music 5.0 on Juno. This happens from Juno Beta1 AFAIK

**Comment by DanyGee** [comment]
I can confirm it on my machine too. No sorting possible.

**Comment by Breakfast-for-Pigeons** [comment]
Not only is this a problem in List View and Column View, it's also a problem in Album View. It appears that Albums are not sorted in any particular order, neither by artist name nor by album title. It appears to be random.
