### ISSUE TITLE
Critical error displayed by starting the app with command line

### ISSUE THREAD

**Issue by ryonakano** [elementary/music#397]
![peek 2018-07-21 09-53](https://user-images.githubusercontent.com/26003928/43030510-fd24ddcc-8ccb-11e8-91bb-3e4473efa604.gif)

1. Type `io.elementary.music` to Terminal and run Music
2. The following error message will be shown so many times

```
** (io.elementary.music:14914): CRITICAL **: 09:54:48.650: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
```

This issue occurs even if we have no music in the music library.

**Comment by Nine-H** [comment]
OK, this is related to the plugin system: when we initialise the iPod and CD plugins they add their output to the playback list in `PlaybackManager`, but because they're usually initialised without a CD inserted and an iPod plugged in they add a reference to a null object which causes the stream of errors.

**Comment by naaando** [comment]
I had this problem too, but after clearing noise's data folder I couldn't reproduce it anymore.
Althrough it's not crashing anymore it kept showing critical messages, so I fixed this and believe this can be the root of this issue, if someone can test my branch or give me a reproducible case of this issue

My branch: https://github.com/naaando/music/tree/fix_null_local_media
My pull request: https://github.com/elementary/music/pull/430

**Comment by ryonakano** [comment]
Closing as this issue is no longer reproducible with the latest master branch

**Comment by ghabit** [comment]
It is appearing to me. Spotted it because started music from terminal to look for some errors, because can't even start music on another user on pc.

**Comment by Qaldak** [comment]
same here.
![image](https://user-images.githubusercontent.com/27882704/76508392-98ae2e00-644e-11ea-930c-dcfe67a74b81.png)

**Comment by vjr** [comment]
> same here.

Have you updated your installation? If I am not mistaken, a recent update to the Music (noise) app has resolved this.

**Comment by Qaldak** [comment]
> Have you updated your installation? If I am not mistaken, a recent update to the Music (noise) app has resolved this.

Yes, my system is up to date.
Music v5.04, elementary OS 5.1.2 Hera

All updated via AppCenter

**Comment by vjr** [comment]
Music should be at 5.0.5 as of last week, you have 5.0.4? I could be mistaken though.

**Comment by Qaldak** [comment]
According App Center: 5.0.4 - 17. Apr. 2019
I can not update to 5.0.5 via App Center. Why not? It's the standard player for elementary OS. 
Do I have really to install / build manually?

**Comment by MrMarukesu** [comment]
Seems that the 5.0.5 only got into the daily repo
