### ISSUE TITLE
When using ctrl selection, second selection is always deselected

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/music#41]
Ver 0.4.0.3

Steps to reproduce:

- Hold ctrl, select first song
- select 2nd song
- select 3rd song, 2nd selection becomes unselected

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.
