### ISSUE TITLE
Translations breaking icons paths

### ISSUE THREAD

**Issue by naaando** [elementary/music#412]
Recently some users on telegram reported icons missing, I guess this is caused by translations on icon's path. For example:

Icon[ca]=reproductor-àudio-multimèdia
Icon[pt]=leitor de audio multimédia
Icon[zh_CN]=多媒体-音频-播放器

Leads to missing icons as the original path would be 'multimedia-audio-player' instead.

**Comment by danrabbit** [comment]
This needs to be solved on Weblate. Translators need to leave these icon names alone

**Comment by danrabbit** [comment]
It's just a quirk of how the build system works. So far there's no technical solution, we just need to not translate that string

**Comment by danrabbit** [comment]
Once again, this can't be solved in this repo. Please make changes in Weblate. Locking this thread since nothing can be done on GitHub
