### ISSUE TITLE
Playlists completely broken

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#415]
Adding any media to a playlist causes the entire library to be added to the playlist, you cannot remove media from the playlist.

Expected Behaviour: adding and removing media to playlists like every other music player

I noticed that in the SQLite db the media key showed an integer (13 the first time and 51 on the second test) and not a composite key of tracks like a string field would suggest.

**Comment by jeremypw** [comment]
@Nine-H Is this bug present in the current version?  Are you referring to a standard or "smart" playlist?  How are you adding media (context menu/DnD ...). Please give a more informative title to issues.

**Comment by jeremypw** [comment]
Closing as old and no response.
