### ISSUE TITLE
Music crashes when a CD is mounted

### ISSUE THREAD

**Issue by 413Michele** [elementary/music#437]
Steps to riproduce:
1. start Music
2. insert (or mount from files a CD) and wait for it to be mounted
3. Music crashes
4. Trying to reopen it causes a new crash

Error from terminal output:
```
(io.elementary.music:5492): GLib-GObject-CRITICAL **: 01:33:08.477: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(io.elementary.music:5492): GLib-GObject-WARNING **: 01:33:08.477: cannot register existing type 'NoiseTreeViewSetup'

(io.elementary.music:5492): GLib-CRITICAL **: 01:33:08.477: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:5492): GLib-GObject-CRITICAL **: 01:33:08.477: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Errore di segmentazione
```

The last line is italian, should be segfault (pretty obvious maybe, but better to be sure)

BONUS:
Related to [this](https://github.com/elementary/music/issues/397) bug, when launching Music without mounting a CD it works as intended, but with a continuos stream of critical errors:

`** (io.elementary.music:5492): CRITICAL **: 01:32:58.371: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
`

EDIT:
Version is eOS 5.0 freshly installed (with NVIDIA drivers, but quite sure the problem was already there)

**Comment by ptrbojko** [comment]
Same for me, 5.0:

```
(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:08.403: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:08.442: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:08.516: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type 'GeeBidirSortedSet' of the property on the interface 'GeeBidirSortedSet'


(io.elementary.music:18239): GLib-GObject-WARNING **: 10:54:09.236: cannot register existing type 'NoiseViewWrapper'

(io.elementary.music:18239): GLib-CRITICAL **: 10:54:09.236: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:09.236: g_type_register_dynamic: assertion 'parent_type > 0' failed
** Message: 10:54:09.236: LastFM.vala:42: Activating Last.fm plugin
** Message: 10:54:09.236: AudioPlayer.vala:37: Activating AudioPlayer Device plugin
** Message: 10:54:09.236: iPod.vala:37: Activating iPod Device plugin
** Message: 10:54:09.236: CDRom.vala:37: Activating CD-Rom Device plugin

** (io.elementary.music:18239): CRITICAL **: 10:54:09.237: noise_playback_manager_add_playback: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:09.486: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:09.486: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:10.211: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:10.212: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:10.437: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

** (io.elementary.music:18239): CRITICAL **: 10:54:10.437: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:10.449: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(io.elementary.music:18239): GLib-GObject-WARNING **: 10:54:10.449: cannot register existing type 'NoiseTreeViewSetup'

(io.elementary.music:18239): GLib-CRITICAL **: 10:54:10.449: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:18239): GLib-GObject-CRITICAL **: 10:54:10.449: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

**Comment by AnwarShah** [comment]
I think this issue is also related https://github.com/elementary/music/issues/391

**Comment by 4jNsY6fCVqZv** [comment]
The crash is still valid and takes place with every CD (they are always original CDs, no copies).  

I have made various observations and tried things out.  

* Songs that I select from the tested CDs in Files lead to a crash when I use "Open in Music" from the context menu. Music seems to open for a short time, but closes immediately. From this point on, you can no longer start Music. The same crash occurs.

To test further, I have to eject the CD first and then insert it again. Otherwise the Music won't start at all.

* I also tried the options "Import Music" and "Change Music Folder" in Music to open the already mounted audio CDs. Unfortunately, this always leads to the same crash as I described in the previous step.

What could a solution to this problem look like?

In this state the app is unfortunately not usable for me.

And Rhythmbox works, but wouldn't be my first choice ;-)

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit Sorry for pinging. I see you're working on music right now. Can you help with this issue here as well?

**Comment by alexfacciorusso** [comment]
Same here. Whenever an audio CD is mounted, Music crashes or not opens at all.

**Comment by whoppix70** [comment]
** (io.elementary.music:2245): CRITICAL **: 11:42:02.713: noise_playback_manager_get_current_media: assertion 'self != NULL' failed

(io.elementary.music:2245): GLib-GObject-CRITICAL **: 11:42:02.851: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(io.elementary.music:2245): GLib-GObject-WARNING **: 11:42:02.852: cannot register existing type 'NoiseTreeViewSetup'

(io.elementary.music:2245): GLib-CRITICAL **: 11:42:02.852: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.music:2245): GLib-GObject-CRITICAL **: 11:42:02.852: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Speicherzugriffsfehler
