### ISSUE TITLE
All songs are being added to queue after click on a single music in the library

### ISSUE THREAD

**Issue by matheuszabin** [elementary/music#444]
I have 36 songs on my library, and after I click on any music there, the whole library are added to the queue. As you can see (through the queue's label), 36 songs are added to the queue after a single click on any song.
![captura de tela de 2018-10-19 11 21 37](https://user-images.githubusercontent.com/33835731/47224268-7d420f00-d391-11e8-9034-d362029e99d5.png)
After click:
![captura de tela de 2018-10-19 11 21 54](https://user-images.githubusercontent.com/33835731/47224271-7f0bd280-d391-11e8-9542-2a3fd8aae4f1.png)

**Comment by ryonakano** [comment]
Duplication of #438?

**Comment by matheuszabin** [comment]
> Duplication of #438?
Oops, sure, I guess is a duplication...
