### ISSUE TITLE
Is Music used on a daily basis by its developers?

### ISSUE THREAD

**Issue by eljefuri** [elementary/music#447]
_[This is probably not appropriate fodder for an issue; moderators feel free to tell me where it should go.]_

Are the developers of this app music fans with moderate-to-large collections of downloaded, locally stored music, or if they are primarily users of things like Spotify? The Juno release of Music seems very untested, crash-prone, and features questionable UX choices (e.g. the default queueing behavior). If that is because the developers don't see a lot of future in the core idea of Music (and consequently don't use it much themselves), then that would be helpful to know.

I can understand that the idea here was to provide some sensible default app which also grabbed the "namespace" for music fans, but I wonder who it is intended to serve. If you believe that there is a target for this app in Elementary, why not bundle @artemanufrij 's very stable Melody as default?

It is very frustrating to see something like Music as a default Elementary application. Those should all be _absolutely excellent_ since they will presumably be among the first experiences for new users. But it is also quite disappointing for someone like myself who does have a great deal of "offline" music. I really _want_ to be able to love how it all _just works_.

Sorry for the downer guys, but let's either get this app in shape or drop it.

**Comment by aadilayub** [comment]
There has been discussion previously (I recall seeing a comment on reddit) about deprecating Music because it is difficult to maintain legacy codebase. 

The Loki version of Music was relatively stable in my experience (meaning all the features worked as intended, but the app crashed occasionally). Although the design of the Juno version of Music is an improvement, the app itself has become unusable (for me, mainly due to the queueing bug). On the plus side, it seems to have gotten better at recognizing track metadata.

This discussion probably belongs in the community Slack, not in the issue tracker.

**Comment by tintou** [comment]
Until we can integrate with online streaming services (see #167) it might be the last appearance of Music in elementary.
I'm personally not using it since a few years now.

**Comment by eljefuri** [comment]
@aadilayub This seems like something that needs to be slowly reasoned out by itself long-form, with all arguments present, not mixed with every other thread and topic as it would be in Slack. Agreed re the Loki version being quite alright.

@tintou Would it be possible to keep this as an open issue for another few weeks or so, just to keep attention on it? I would like to know what is going on with Elementary Music and I don't see any other place where this can be discussed long-form with developers (per above, Slack doesn't really cut it).

**Comment by aljelly** [comment]
Personally I use Music almost daily.

I'm strongly against removing the Music app entirely. Please just either fix the issues with Music or rewrite it. Don't throw the baby out with the bathwater.

**Comment by janxkoci** [comment]
I still didn't manage to import my library in Juno version of Music, even on my ultrabook. It always crashes at some point. Melody is done with the whole import in like 2 minutes. Byte is little slower and has some issue with CPU usage, but it still imports the library even on Atom netbook.

Mostly I use Audacious though, as I don't really "get" the idea of a library that needs to be imported (same with photos btw). I just don't like it's UI so much, so I try out alternatives at times, but it's still my go-to player.
