### ISSUE TITLE
can't import music 

### ISSUE THREAD

**Issue by Ilham79** [elementary/music#456]
not import music from library music folder

**Comment by Mohelm97** [comment]
Hi Ilham,
How can I reproduce the problem?
What kind of files wasn't imported? or the whole music folder, and are you sure that "Music folder location" is correct in the preferences?

**Comment by Mohelm97** [comment]
Hi @jsmwoolf,
Yeah, I've tried to work in this in particular :laughing: and It seems that It's the whole load/save playlist is broken, if you fix the playlist loading issues that would be brilliant.

I think @Ilham79 says that nothing is imported from music folder, But I'm not sure, and hope she will reply soon.

Cheers mate ;)

**Comment by Ilham79** [comment]
thank you for entering, my music app in elementary OS can now run well

**Comment by Mohelm97** [comment]
@Ilham79 Happy to hear that :D But I did nothing literally haha, If you experience any issues please post it here ;)
