### ISSUE TITLE
10 critical errors per second when Music is started for the first time

### ISSUE THREAD

**Issue by decathorpe** [elementary/music#466]
1) Install elementaryOS Juno
2) Launch io.elementary.music from a terminal
3) See infinitely many critical error messages scroll by:

```
** (io.elementary.music:1587): CRITICAL **: 12:11:43.512: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
```

This error message is printed twice every 200 ms.

**Comment by ryonakano** [comment]
Duplicate of #397?

**Comment by decathorpe** [comment]
Yes, probably. Closing this issue in favor of #397
