### ISSUE TITLE
Music doesn't read embedded Cover art

### ISSUE THREAD

**Issue by lainsce** [elementary/music#47]
I've seen this with my library of music, it doesn't pick up that the files have embedded cover art in them, instead, it needs a cover.jpg file to be able to show cover art, which isn't normal behavior.

**Comment by hellpe** [comment]
I think this may be related to an old Launchpad ticket I've been trying to help solve by posting a bounty on it: https://www.bountysource.com/issues/843250-album-art-not-populated-until-a-song-from-any-given-album-is-played-first-art-embedded-in-id3-tag
