### ISSUE TITLE
Album view sorting by album name?

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/music#489]
I hope that this is not intentional, it should be by the artist. At least give us an option to change this.

**Comment by Mohelm97** [comment]
I think we should add an option to change this

**Comment by WebShapedBiz** [comment]
Nice. Thank you for your quick reply.

Cheers.

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.
