### ISSUE TITLE
Clicking on an Album cover displays a weird popup

### ISSUE THREAD

**Issue by bigfatbird** [elementary/music#51]
When clicking on an album cover a popup is displayed showing the single tracks of the album.

Instead it would be better if the main windows transforms and shows the list of the tracks directly.

maybe the album cover can move to the side or to the top of the window and display the content next to it or a new site inside the window can be opened and a nav bar in the top can be displayed

**Comment by danrabbit** [comment]
Fixed in #145

**Comment by bigfatbird** [comment]
Oh. My. God. ❤️
