### ISSUE TITLE
Music uses different background color for selected items to Files, Code etc.

### ISSUE THREAD

**Issue by jeremypw** [elementary/music#535]
Music provides its own application.css which includes an orange color for the background of selected items.  This clashes with the blue color used in other core elementary apps.  There does not seem to be a good reason for this.

**Comment by cassidyjames** [comment]
@jeremypw Music sets its own accent color, which is supported in the stylesheet. The idea is to bring more app-specific branding into core apps, and Music is ones of the first places we've done this. Calendar also uses a green accent color, though.

**Comment by jeremypw** [comment]
OK, if that's the intention. Note, the calendar indicator has a blue accent whereas the calendar app has blue but I guess thats a wip.

Maybe Files should have a grey accent?

**Comment by cassidyjames** [comment]
Yeah good call regarding the indicator, I'll file an issue and we can discuss that there. That could be some nice consistency. 

The default accent is blue and we don't really care for a strong Files "brand" imho, so I think blue is fine there.
