### ISSUE TITLE
In-app volume control?

### ISSUE THREAD

**Issue by sprite-1** [elementary/music#554]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Scenario: I listen to songs while playing games. I can't lower the volume of the music to hear the dialogues of the characters in the game. The game doesn't have fine tune control of volume (can only turn voice on or off) Plus many other use-cases where lowering the volume of just the playing music instead of the whole system, is completely valid.

**Describe the solution you'd like**

A dedicated volume control that resides in the app just like any other media player in existence.

**Existing work**

It exists in every media player I've used.

**Describe alternatives you've considered**

I've considered not listening to music altogether while playing games

**Additional context**

I know [there was an issue](https://github.com/elementary/music/issues/386) for this which was marked "Out of Scope" which is pretty bizarre to me since this is a basic feature that for some reason is not present

**Comment by tintou** [comment]
It's the design choice of the audio player to not cover volume control per-app, ideally, the dialogs of the game should lower the sound of the music or pause it when triggered (as navigation direction is doing with music in modern cars). This could be solved if the game was providing its audio "role" and with the use of the right PipeWire profile once we have PipeWire support.

**Comment by sprite-1** [comment]
I think that's a tall order when most games don't even have a Linux port to begin with
