### ISSUE TITLE
Make available as a Flatpak on Flathub?

### ISSUE THREAD

**Issue by JaneSmith** [elementary/music#564]
Hello. This application looks very nice, and I am interested in running it on Fedora Silverblue. The intended way to install apps on Silverblue is via Flatpak. I've had a look on Flathub and I can't find it on there, nor can I find any mention of Flatpak in this repository.

Would you be able to consider packaging this as a Flatpak? Thanks!

**Comment by cassidyjames** [comment]
We plan to use Flatpak for elementary apps, but it doesn't make sense to host them in an elementary remote as well as Flathub. Instead, we'll likely host them alongside all the other AppCenter apps. If you're on a non-elementary OS, you will be able to add the remote just like Flathub and install AppCenter apps. However, this work is ongoing and not ready yet.
