### ISSUE TITLE
Replace all instances of Gtk.Toolbar

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#568]
This has been removed in Gtk4

**Comment by pablojimpas** [comment]
Related info:
https://docs.gtk.org/gtk4/migrating-3to4.html#gtktoolbar-has-been-removed
https://valadoc.org/gtk+-3.0/Gtk.Toolbar.html
https://valadoc.org/gtk4/Gtk.Box.html

Two declarations found:
![Captura realizada el 2021-04-09 23 23 52](https://user-images.githubusercontent.com/51208565/114242157-b835c400-998a-11eb-97e1-cd65e84915aa.png)
