### ISSUE TITLE
Playback buttons are disabled on startup

### ISSUE THREAD

**Issue by vjr** [elementary/music#570]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The playback buttons (previous, play/pause, forward) are disabled when starting Music even with available files in the library. Also after importing music for the first time.

### To Reproduce
1. Copy music files to the user Music folder.
2. Open Music app and let it detect/import the music.
3. Note that when step 2 is done, the playback buttons remain disabled.
4. Only way to start playing music is to double-click on a media entry in the list.
5. Close and reopen Music, same issue even though music files are available.

### Expected behavior

Music should be able to start with playback buttons enabled when media is available.

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by Dirli** [comment]
Disagree. Playback buttons should only be available if there are tracks in the queue. The presence of tracks in the library does not mean that they should be played.

**Comment by vjr** [comment]
I believe the tracks are in queue. The playback buttons do not get enabled if I just select (click on) a track. The track will start playing if I double click on one though, and only then the playback buttons get enabled.
