### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by poetgrant** [elementary/music#584]
Is there any chance that you guys will possibly be adding podcasts to Music? I would really love it if that happened.

**Comment by cassidyjames** [comment]
Nope. I wrote a [blog post about this](https://blog.elementary.io/a-music-app-shouldnt-be-a-podcast-app/) back in 2014, and it still holds true. For podcasts, we recommend checking out [Vocal in AppCenter](http://appcenter.elementary.io/com.github.needle-and-thread.vocal/).
