### ISSUE TITLE
Unable to uninstall music

### ISSUE THREAD

**Issue by Timetry** [elementary/music#596]
Application state not set as installed in AppCenter for package: 音乐

**Comment by jeremypw** [comment]
Seems to be set OK on recently installed Elementary 6:

![image](https://user-images.githubusercontent.com/10513844/92305678-4bd08d80-ef81-11ea-906e-2bf000ea21a0.png)

**Comment by jeremypw** [comment]
Presumably you can use the terminal and uninstall with `sudo apt uninstall noise`?

**Comment by Timetry** [comment]
sudo apt remove noise .success ,thank you
