### ISSUE TITLE
Energy saving options should be blocked when music is playing

### ISSUE THREAD

**Issue by Heiko-M** [elementary/music#60]
Currently energy saving options, such as turning off the screen, pause music. It's somewhat annoying when you turn on music, leave the laptop to find a comfortable spot to chill, just to realize a few minutes later, when your music stops playing, that the screensaver has set in.

**Comment by matzipan** [comment]
This is an OS issue which has been discussed time and time again and we believe can be fixed more easily when we move to Wayland, as it's caused by a limitation of the X.org server. Some explanation as of why can be found [here](https://xubuntu.org/news/screen-locking-in-xubuntu-14-04/).
