### ISSUE TITLE
Music: Make Top Display look batter.

### ISSUE THREAD

**Issue by BAProductions** [elementary/music#609]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

width Gtk.STYLE_CLASS_TITLEBAR
![screenshot](https://user-images.githubusercontent.com/2386630/95617005-bff6c900-0a38-11eb-8702-0b351b14dafe.png)

width Gtk.STYLE_CLASS_ENTRY
![Screenshot from 2020-10-09 13 34 16@2x](https://user-images.githubusercontent.com/2386630/95617008-c08f5f80-0a38-11eb-847b-7fa0fd363d86.png)

By switching from
Gtk.STYLE_CLASS_TITLEBAR to Gtk.STYLE_CLASS_ENTRY the application tends look nicer, But with third party themes the look bake.

**Describe the solution you'd like**

Music: Make Top Display look batter.

By switching from
Gtk.STYLE_CLASS_TITLEBAR to Gtk.STYLE_CLASS_ENTRY the application tends look nicer, But with third party themes the look bake.

https://github.com/MC-OS/music/commit/79abe3117b854df92475af783ea4a4d8eb49dd4d

**Existing work**

Nope as it a design change an not a feature.

**Describe alternatives you've considered**

Using custom Styling witch all those it works with all themes it just does no look as nice Gtk.STYLE_CLASS_ENTRY.  

**Additional context**

![Screenshot from 2020-10-09 13 34 16@2x](https://user-images.githubusercontent.com/2386630/95616523-e9fbbb80-0a37-11eb-9507-00f98f973c63.png)
![Screenshot from 2020-10-09 13-53-02@2x](https://user-images.githubusercontent.com/2386630/95616524-ea945200-0a37-11eb-8f63-16eff5ce2ce3.png)

**Comment by danrabbit** [comment]
Same comments as on the PR. I'm not sure what goal this is meant to achieve. Contrast is already quite high here and adding this extra box really increases the size of the headerbar which isn't desirable. So I'm going to close this as "Design conflict"
