### ISSUE TITLE
How do i remove io.elementary.music?

### ISSUE THREAD

**Issue by K4mey** [elementary/music#617]
$ sudo pacman -Rns io.elementary.music                                             
error: target not found: io.elementary.music

**Comment by vjr** [comment]
Is it io.elementary.music or still just `noise` ? Try removing `noise` package?

**Comment by danrabbit** [comment]
@K4mey if you're on Arch, that's going to depend on how it was packaged for your distro. elementary doesn't provide packages for Arch, so this isn't something that is in the scope of this repo. Closing as "out of scope"
