### ISSUE TITLE
Don't rely on Zeitgeist for History playlist

### ISSUE THREAD

**Issue by danrabbit** [elementary/music#630]
## Problem

We currently rely on Zeitgeist to power the "History" playlist, but Zeitgeist is unmaintained and we should move away from it.

## Proposal

If we need to rely on an external service for this, it should be Tracker

**Comment by davidmhewitt** [comment]
Do we have any plans of how we're going to use Tracker for this? Tracker is a file indexing service for searching for files. It doesn't natively track things like how often you listened to/opened a file or how long you spent using an application AFAIK (which is what we need replacements for here and in the applications menu).

It sort of seems like Tracker can act as some kind of generic database too, so in theory it would be possible to extend it with some elementary recent files, applications, etc stuff. But I don't think it does that out of the box.

There's some recent files functionality built into GTK which I believe is what powers the recent documents list in the file chooser and Nautilus https://valadoc.org/gtk+-3.0/Gtk.RecentManager.html , but unsure whether/how this fits.

**Comment by jhaygood86** [comment]
One thing to: Zeitgeist has actually had a recent release (1.0.3), so it might not be 100% dead. There is also activity in its GitLab instance: https://gitlab.freedesktop.org/zeitgeist/zeitgeist/activity

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Music and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Music.
