### ISSUE TITLE
Circle around music control buttons

### ISSUE THREAD

**Issue by nielsvl95** [elementary/music#637]
When opening the Music application, there is a circle in the accent color around the Previous button, as you can see in the screenshots. Also, when pressing play/pause or next, the circle stays on those buttons. However, after selecting something else like a song or something in the sidebar, the circle will go away.

![Schermafdruk van 2021-05-22 00-34-12](https://user-images.githubusercontent.com/66212886/119205109-99e9da80-ba97-11eb-9487-612f10e802ae.png)
![Schermafdruk van 2021-05-22 00-40-10](https://user-images.githubusercontent.com/66212886/119205111-9a827100-ba97-11eb-91a7-2c1a0c15e163.png)

## Expected Behavior
I believe there is no need for a circle at all, so in my opinion this can be removed altogether. Otherwise it should only be on hovering, which it doesn't right now.

## Steps to Reproduce
1. Open Music application
2. Click on media controls

## Platform Information
elementary OS 6 beta
Linux kernel 5.8.0-50-generic
All updates applied as of Friday 21 May 2021

**Comment by danrabbit** [comment]
This is expected and happens in all tool items for all apps to indicate keyboard focus
