### ISSUE TITLE
Theme accent colors are not followed

### ISSUE THREAD

**Issue by AI-ien** [elementary/music#663]
## What Happened
Selected theme accent colors are not followed (Screenshot example system selected Blueberry accent).

## Expected Behavior
Toggle buttons are expected to follow selected theme color scheme.

## Steps to Reproduce
Open settings dialog.

## Platform Information
OS: elementary OS 6 Odin x86_64 
Kernel: 5.11.0-37-generic
io.elementary.music: 5.1.1

![Screenshot from 2021-09-29 13 41 48](https://user-images.githubusercontent.com/33252703/135254258-c9c1b60c-42a0-4c05-b36a-ac73785767f2.png) ![Screenshot from 2021-09-29 13 41 56](https://user-images.githubusercontent.com/33252703/135254278-d27d2126-b6ed-419f-8264-0080b103f984.png)

**Comment by cassidyjames** [comment]
@AI-ien as mentioned in that text under the Accent option (cut off in your screenshot), apps can always choose to use their own accent color depending on their branding. Music's accent is orange, Calendar's is green, etc.

**Comment by AI-ien** [comment]
Ok, understood. This is intended. I just assumed that built in apps strictly follow system color scheme.
