### ISSUE TITLE
Row CSS styling enhancement

### ISSUE THREAD

**Issue by itprojects** [elementary/music#666]
### Problem

Modern music players have this great feature, where rows of tracks have alternating background colours, which looks amazing and makes it easier to look at.

It would be fantastic to have that in Elementary Music (Noise).

### Proposal

Please, add the alternating row background colours feature.

### Prior Art (Optional)

![](https://community.linuxmint.com/img/screenshots/quodlibet.png)

![](https://www.wideanglesoftware.com/support/touchcopy/images/exclamation-mark.jpg)

**Comment by rakshit087** [comment]
I think this issue belongs to the stylesheet.

**Comment by itprojects** [comment]
@tintou What do you think about the feature, in the general sense? (Thank you for the link you included above.)
