### ISSUE TITLE
Looping over 1 song

### ISSUE THREAD

**Issue by SuburbanFilth** [elementary/music#71]
I might be missing something, but there is no option that loops over a single song. Is that a bug or something that has not been implemented ?

**Comment by Bat41** [comment]
You can do it by right-clicking the "loop" button in the bottom bar. But I agree that it's not very natural, it would be better if we had like most music players 3 states for this button.

**Comment by SuburbanFilth** [comment]
i completely missed it. Thank you for the info!

**Comment by yeboahnanaosei** [comment]
C'mon elementary????? Why do I have to right click just to loop only one song? I use elementary but sometimes your design choices are too painful to use.

**Comment by SuburbanFilth** [comment]
the salt is real ... The app is opensource so you are free to modify it if you want to save the 2 clicks

**Comment by yeboahnanaosei** [comment]
True but don't forget some things are just basic and we all can't learn Vala right?

**Comment by yeboahnanaosei** [comment]
@Bat41Exactly!!!
