### ISSUE TITLE
Adapt other gtk themes 

### ISSUE THREAD

**Issue by LinuxWOW** [elementary/music#718]
### Problem

Only elementary themes and icons work with the new music player, If you switch to another theme outside of elementary app won't look as it should.

### Proposal

fix so you can add what ever theme you want or icons.

**Comment by danrabbit** [comment]
Sorry but this is a “won’t fix”. Music relies on the elementary stylesheet and icons to work correctly

**Comment by LinuxWOW** [comment]
Isn't that the whole point of Linux? So you can use what you want?
