### ISSUE TITLE
Can't drag and drop folders  into playlist

### ISSUE THREAD

**Issue by BugFixesAndPerformanceImprovements** [elementary/music#734]
### What Happened?
Dragging and dropping a folder or files into the playlist gives an error message "invalid file was not added to the queue." 

See the following video for demonstration.

[Can't drag and drop folders or files into playlist.webm](https://user-images.githubusercontent.com/58829078/207995984-3d725cf8-6001-439c-9e8a-da4f8c081ee0.webm)

### Steps to Reproduce
1. Click/select a folder containing music files or music files invidividually
2. Drag and drop them into the playlist
3. The error message is shown and the files are not added to the playlist

### Expected Behavior
The music files or folders and its contents should be added to the playlist. 

### OS Version
6.x (Odin)

### Software Version
7.0.1

**Comment by hrstwn** [comment]
I have the same problem

**Comment by jeremypw** [comment]
This worked for me when dragging a single `.ogg` file onto an empty playlist. (Elementary OS7).  This issue is related to  https://github.com/elementary/music/issues/709.
