### ISSUE TITLE
Search mechanism in the app

### ISSUE THREAD

**Issue by Ewertonios** [elementary/music#762]
### Problem

We can't search for a song directly in the app in a playlist.

### Proposal

Build a search option in the header bar that allows you to search for a song in a playlist.

### Prior Art (Optional)

![searchbar](https://github.com/elementary/music/assets/107805966/19fddf47-60b1-42ee-b3d4-43c5a2ceb9b6)

**Comment by jeremypw** [comment]
It should not be too hard to implement a simple text search within the list. Would this suffice (at least as a start)? Fully searching metadata might take more work.

**Comment by Ewertonios** [comment]
It would definitely be a good start. Thank you very much!
