### ISSUE TITLE
Change package name to noise-audio-player?

### ISSUE THREAD

**Issue by waldyrious** [elementary/music#78]
This is essentially the same issue as https://github.com/elementary/videos/issues/45. I couldn't find any issues in this repo referring to this, so I thought I'd open this even if just to serve for future reference.

My question is whether it makes sense (or is planned) for this app's .deb package (i.e. as it appears in `apt`) to be named `noise-audio-player`, or `noise-music-player` just like e.g. [elementary/scratch](https://github.com/elementary/scratch) is named `scratch-text-editor` and [elementary/calendar](https://github.com/elementary/calendar) is named `maya-calendar`, etc.

I am sure this has already been discussed, in which case this issue may be moot; pointers to where this information could be found would be appreciated.

**Comment by Nine-H** [comment]
most of the apps are switching to RDNN so I think the package will be io.elementary.music, scratch is going to be io.elementary.code and this will be reflected in binary names, .desktop files and settings keys.

**Comment by waldyrious** [comment]
> and this will be reflected in binary names, .desktop files and settings keys.

I understand that. My question is whether this will also affect the .deb package names as well.

**Comment by Nine-H** [comment]
probs. not till juno tho.

**Comment by danrabbit** [comment]
I'm going to close this issue for Music since packaging doesn't happen in this tree

**Comment by waldyrious** [comment]
> packaging doesn't happen in this tree

@danrabbit fair enough. Where is it tracked / trackable, then? I mean, the decision about package names in particular.
